//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STF_CharacterPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STF_CharacterPlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job:Starter
        ///Crew Dog:Yes
        ///Mechanic:Yes
        ///Electronics Tech:Yes
        ///Gunner:Yes
        ///Soldier:Yes
        ///Pistoleer:Yes
        ///Sniper:Yes
        ///Swordsman:Yes
        ///Assassin:Yes
        ///Combat Medic:Yes
        ///Doctor:Yes
        ///Diplomat:Yes
        ///Zealot:No
        ///Hyperwarp Navigator:No
        ///Wing Tech:No
        ///Exo-Scout:No
        ///Scavenger:No
        ///Xeno Hunter:No
        ///Commander:No
        ///Pilot:No
        ///Wing Commando:No
        ///Merchant:No
        ///Smuggler:No
        ///Pirate:No
        ///Bounty Hunter:No
        ///Military Officer:No
        ///Explorer:No
        ///Spy:No
        ///Engineer:No
        ///Quartermaster:No
        ///Wing Bomber:No
        ///Wing Leader:No
        ///.
        /// </summary>
        internal static string job_list {
            get {
                return ResourceManager.GetString("job_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Size:Current Mass:Pilot:Ship Ops:Gunnery:Electronics:Navigation:Cargo:Max Crew:Max Officers:Jump Cost:Armour:Fuel Tank:Guest:Prison:Medical:Shield
        ///Bridge:Medium:300:5:3:0:4:5:0:0:1:0:0:0:0:0:0:0
        ///Scout Bridge:Small:100:4:2:0:3:3:0:0:3:0:0:0:0:0:0:0
        ///Capital Bridge:Large:600:9:5:0:8:8:0:0:1:0:0:0:0:0:0:0
        ///Bridge 2:Medium:300:6:3:0:5:5:0:0:1:0:0:0:0:0:0:0
        ///Bridge 3:Medium:300:6:4:0:5:6:0:0:1:0:1:0:0:0:0:0
        ///Bridge 4:Medium:300:7:4:0:5:7:0:0:1:0:1:0:0:0:0:0
        ///Scout Bridge 2:Small:100:5:3:0:4:4:0:0:3:0:0:0: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ship_components {
            get {
                return ResourceManager.GetString("ship_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill
        ///Blades
        ///Evasion
        ///Stealth
        ///Rifles
        ///Intimidate
        ///Pistols
        ///Doctor
        ///Tactics
        ///Command
        ///Ship Ops
        ///Gunnery
        ///Repair
        ///Negotiate
        ///Electronics
        ///Explore
        ///Navigation
        ///Pilot.
        /// </summary>
        internal static string skill_list {
            get {
                return ResourceManager.GetString("skill_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:1-Name:1-Num:2-Name:2-Num:3-Name:3-Num:Job
        ///1:Ship Ops:4:Gunnery:1:Repair:1:Crew Dog
        ///2:Ship Ops:4:Gunnery:1:Repair:2:Crew Dog
        ///3:Ship Ops:4:Gunnery:2:Repair:2:Crew Dog
        ///4:Ship Ops:5:Gunnery:2:Repair:2:Crew Dog
        ///5:Ship Ops:5:Gunnery:2:Repair:3:Crew Dog
        ///6:Ship Ops:6:Gunnery:2:Repair:3:Crew Dog
        ///7:Ship Ops:6:Gunnery:2:Repair:4:Crew Dog
        ///8:Ship Ops:7:Gunnery:2:Repair:4:Crew Dog
        ///9:Ship Ops:7:Gunnery:3:Repair:4:Crew Dog
        ///10:Ship Ops:8:Gunnery:3:Repair:4:Crew Dog
        ///11:Ship Ops:9:Gunnery:3:Repair:5:Crew Dog        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skill_per_job_list {
            get {
                return ResourceManager.GetString("skill_per_job_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Mass:Speed:Agility:Fuel Cost:Combat Cost:Safety:Range Cost
        ///M2400 Void Engine Balanced:2400:27:27:2:6:6:3
        ///M2400 Void Engine Longhaul:2400:27:27:1:10:7:3
        ///M3400 Void Engine Traveler:3400:29:24:2:9:7:3
        ///M3400 Void Engine Chaser:3400:24:29:2:10:6:2
        ///M3400 Void Engine Balanced:3400:24:24:2:8:5:3
        ///M3400 Void Engine Longhaul:3400:23:23:1:7:8:3
        ///M5000 Void Engine Traveler:5000:23:16:3:12:9:4
        ///M5000 Void Engine Balanced:5000:19:19:2:13:7:4
        ///M5000 Void Engine Chaser:5000:18:22:2:15:8:3
        ///M6000 Void Engine Longh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_engine_data {
            get {
                return ResourceManager.GetString("stf_engine_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship:Current Mass:Max Mass:Price:Total Slots:Large:Mid:Small:Hull:Armour:Shield:Max Officers:Max Crew:Cargo:Engine:Speed:Agility:Fuel Cost:Fuel Tank:Fuel Range:Jump Cost:Pilot:Navigation:Ship Ops:Electronics:Gunnery:Tier
        ///Juror Class:3045:3400:160000:15:2:3:10:1100:10:10:4:24:25:M3400 Void Engine Balanced:24:0:2:95:47:21:13:17:21:14:15:0
        ///Paladin Cruiser:4890:5000:260000:19:4:5:10:1500:8:7:5:30:50:M5000 Void Engine Balanced:19:0:2:195:97:24:14:17:28:18:20:0
        ///Fidelis Cutter:5835:6000:375000:23:4:7:12:2000:9: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STF_Ship_Data {
            get {
                return ResourceManager.GetString("STF_Ship_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship:Component
        ///Juror Class:M3400 Void Engine Balanced
        ///Juror Class:Barracks 3
        ///Juror Class:Officer Cabin
        ///Juror Class:Cargo Hold 1
        ///Juror Class:Passenger Cabin
        ///Juror Class:Bridge
        ///Juror Class:Basic Hyperwarp Drive
        ///Juror Class:Light Railgun
        ///Juror Class:Hellfire Torpedo
        ///Juror Class:Weapons Locker A1
        ///Juror Class:Officer Cabin
        ///Juror Class:Armored Bulkheads
        ///Juror Class:Hellfire Torpedo
        ///Juror Class:Phoenix Lance
        ///Juror Class:Officer Cabin
        ///Vulture Liner:M3400 Void Engine Balanced
        ///Vulture Liner:Barracks  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STF_Ship_Default_Comp {
            get {
                return ResourceManager.GetString("STF_Ship_Default_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Rank:Description:Cooldown:Job:Type
        ///Slash:1:Auto-granted attack for carring a Blade:1::
        ///Open Fire:1:Auto-granted attack for carring a Pistol:1::
        ///Short Burst:1:Auto-granted attack for carring a Rifle:1::
        ///Aura of Command:1::30:Commander:SKILL SAVE
        ///Steady Hands:1::60:Commander:
        ///Discerning Glance:1:When Recruiting, new crew member gains improved Attributes and you discover one of their hidden Traits.:30:Commander:RECRUIT
        ///Loyalty Rousing:1:In the aftermath of a ship battle, give an inspiring speech wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_talent_job {
            get {
                return ResourceManager.GetString("stf_talent_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Type:Damage:Radiation:Void:Range:AP:Accuracy:Critical Chance:Cripple Chance:Level
        ///Valiant Autocannon:Autocannon:65:0:0:1:1:1:5:30:1
        ///M90 Barrel-Cannon :Autocannon:135:0:0:1:2:2:12:45:2
        ///M92 Barrel-Cannon:Autocannon:75:0:0:1:1:3:15:40:3
        ///M94 Barrel-Cannon:Autocannon:160:0:0:1:2:5:10:55:4
        ///Dual-Linked Autocannon:Autocannon:85:0:0:1:1:6:20:30:5
        ///Vanguard Autocannon:Autocannon:100:0:0:1:1:6:15:25:6
        ///Lionheart Cannon:Autocannon:90:0:0:1:1:10:15:40:7
        ///Phoenix Lance:Lance:100:20:0:2:2:2:15:55:1
        ///Starshot Lan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_weapon_data {
            get {
                return ResourceManager.GetString("stf_weapon_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:Talents
        ///1:1
        ///3:1
        ///6:1
        ///9:1
        ///12:1
        ///15:1
        ///18:1
        ///21:1
        ///24:1
        ///27:1
        ///30:1
        ///32:1
        ///36:1
        ///39:1
        ///44:1.
        /// </summary>
        internal static string talent_points {
            get {
                return ResourceManager.GetString("talent_points", resourceCulture);
            }
        }
    }
}
